# image: node:8.11.3 # can be upgraded, depending on your node version used

# pages:
# cache:
# paths:
# - ./node_modules/

# stage: deploy
# script:
# - npm install
# - npm run build
# - mv build/* public/
# artifacts:
# paths:
# - public
# only:
# - master


# image: node:8.11.3 # change to match your node version

# cache:
#   paths:
#     - node_modules/

# before_script:
#   - npm install

# test:
#   stage: test
#   script:
#     - CI=true npm test

# pages:
#   stage: deploy
#   script:
#     - CI=true npm run build
#     - rm -rf public
#     - mv build public
#   artifacts:
#     paths:
#       - public # GitLab pages serve from a 'public' directory
#   only:
#     - master # run on master branch


image: node:8.11.3 # can be upgraded, depending on your node version used

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public # mandatory, other folder won't work
  only:
  - master # or dev, the branch you want to publish